version: "3.8"
services:
  spring-mongodb:
    image: mongo
    container_name: spring-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - spring-mongodb-data:/data/db
    networks:
      - spring_mongodb_network
    ports:
      - "27018:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  spring-mongodb-data:
    name: mongodb-data

networks:
  spring_mongodb_network:
    name: spring_mongodb_network